### PR TITLE
Add size output to gcc builds

### PR DESCRIPTION
**Pull request by bremoran**
It might be better to enable this with a config option, rather than on-by-default. But that would make discovery of size output difficult for users, so it might be better to start with this and provide a config option to suppress size output.

cc @hugovincent @paldwort @bogdanm @autopulated @niklas-arm @0xc0170

### CODE REVIEW

**Comment by hugovincent** [comment]
I think we should make this slightly better before merging. The raw output from `size` can be highly misleading for a firmware image. I'd prefer if it could show output something like this:

```
Flash: firmware image:               xx kB
      [configuration data:           xx kB]
      [other:                        xx kB]
       unused:                       xx kB
RAM:   statically allocated:         xx kB
       stack(s):                     xx kB
       available for use at runtime: xx kB
```

(where the square-bracked lines might only apply for some builds -- in other words, the mechanism should allow downstream targets to change its behaviour).

See also: https://github.com/ARMmbed/yotta/issues/534

cc @niklas-arm

**Comment by 0xc0170** [comment]
Our nordic targets show the sections, this is the script they use (https://github.com/ARMmbed/nordic-nrf52832-gcc/blob/master/scripts/memory_info.py).

the output: 

```

[119/119] Linking CXX executable source/example-mbedos-blinky
Memory usage for 'example-mbedos-blinky'
section             size
.data                128
.bss                 848
.heap               3120
.stack              2048

// armcc
[118/118] Linking CXX executable source/example-mbedos-blinky
Memory usage for 'example-mbedos-blinky'
section             size
RW_IRAM1             240
RW_IRAM1            1032
ARM_LIB_HEAP        2824
ARM_LIB_STACK       2048
```

**Comment by jupe** [comment]
I really like to see standard format for memory usage. +1 for @hugovincent suggestion about format..

**Comment by ghost** [comment]
Better to have all targets generate this information in a standard form.  We should also give some thought  as to how this information is made available in a machine readable form without requiring ad-hock parsing of the build log.

**Comment by LiyouZhou** [comment]
@bremoran The `yotta_apply_target_rules` function gets overridden in a child target like this: https://github.com/ARMmbed/target-nordic-nrf51822/blob/master/nordic-nrf51822-gcc/CMake/toolchain.cmake

We need a more specific function to support post build steps such as `yotta_post_build_steps`. And this needs support in yotta @autopulated

**Comment by LiyouZhou** [comment]
FYI a more verbose [script](https://github.com/LiyouZhou/target-mbed-gcc/blob/mem_profile/mem_profile/scripts/parse_map.py) have been produced to print things like this:

```
-----------------------------------
Application code
  EddystoneService             5400
  TLMFrame                      180
  UIDFrame                      142
  URLFrame                      427
  main                          726
  nrfConfigParamsPersistence    271
-----------------------------------
Dependencies
  ble                           417
  ble-nrf51822                14998
  core-util                     806
  dlmalloc                     5832
  mbed-drivers                 1048
  mbed-hal-nrf51822-mcu        1448
  mbed-hal-nrf51dk                2
  minar                        2062
  minar-platform-mbed           108
  nrf51-sdk                    6728
  ualloc                        202
-----------------------------------
External Libraries
  libc_nano                    2761
  libstdc++_nano                 30
-----------------------------------
```

or in verbose mode

```
-----------------------------------
Application code
  EddystoneService             5400
    rodata                      228
    text                       5172
  TLMFrame                      180
    text                        180
  UIDFrame                      142
    text                        142
  URLFrame                      427
    rodata                      121
    text                        306
  main                          726
    bss                           4
    rodata                       40
    text                        682
  nrfConfigParamsPersistence    271
    bss                          93
    data                          8
    text                        170
-----------------------------------
Dependencies
  ble                           417
    bss                          20
    rodata                       35
    text                        362
  ble-nrf51822                14998
    bss                         495
    data                          5
    rodata                      894
    text                      13604
  core-util                     806
    data                         12
    text                        794
  dlmalloc                     5832
    text                       5832
  mbed-drivers                 1048
    bss                          16
    rodata                       96
    text                        936
  mbed-hal-nrf51822-mcu        1448
    bss                          18
    rodata                      136
    text                       1294
  mbed-hal-nrf51dk                2
    text                          2
  minar                        2062
    bss                          24
    rodata                      344
    text                       1694
  minar-platform-mbed           108
    text                        108
  nrf51-sdk                    6728
    bss                         258
    rodata                       88
    text                       6382
  ualloc                        202
    text                        202
-----------------------------------
External Libraries
  libc_nano                    2761
    data                        100
    rodata                      153
    text                       2508
  libstdc++_nano                 30
    bss                           4
    text                         26
-----------------------------------
```

**Comment by LiyouZhou** [comment]
Potentially this in can go into the top level target target-mbed https://github.com/ARMmbed/target-mbed-gcc/pull/26

**Comment by autopulated** [comment]
You could do this in a .cmake include file in a similar way to the [coverage info](https://github.com/ARMmbed/target-mbed-gcc/blob/master/target.json#L37) – adding a post-build step to each executable which is encountered. That should be inherited correctly from the base target (unlike yotta-apply-target-rules, which is a terrible design :fearful: :blush: )

More verbose isn't necessarily better, it's more confusing for anyone who doesn't know what they're looking at!

**Comment by hugovincent** [comment]
> More verbose isn't necessarily better, it's more confusing for anyone who doesn't know what they're looking at!

Exactly. That's why my proposal above is very much simplified, and avoids toolchain-specific language.

**Comment by LiyouZhou** [comment]
@autopulated I looked into coverage.cmake, it only add a compile flag, it does not run a post build step. Am I looking at the wrong place?

**Comment by autopulated** [comment]
The same hook can be used for the post-build step :)

coverage.cmake is included in the build for each target, so you could use [add_custom_command](https://cmake.org/cmake/help/v3.0/command/add_custom_command.html) to add a POST_BUILD command after testing if the TYPE property is EXECUTABLE using get_target_property.

**Pull request closed without merging**
