### PR TITLE
Add support for inline assembly in C files.

### LINKED ISSUE #10: asm keyword not usable with -std=c99
The `asm` keyword does not work with the `-std=c99` compiler switch.  An easy solution to this is to add `-fasm` to the command line as well.

### PR DESCRIPTION
**Pull request by bremoran**
Add the `-fasm` flag to the C family command line.
Fixes #10

### CODE REVIEW

**Comment by bremoran** [comment]
@bogdanm

**Comment by kjbracey** [comment]
-std=c99 seems weird, or at least ambitious, in the first place - it's deactivating a lot of normally-enabled GCC extensions, and lots of code struggles to compile in that environment.

Are you sure you wouldn't rather just use "-std=gnu99"?

**Comment by bogdanm** [comment]
Deactivating GCC extensions is a good thing, since we want our code to compile with other compilers too.

**Comment by 0xc0170** [comment]
Most of the compilers have support for __asm, an example: cmsis headers: https://github.com/ARMmbed/cmsis-core/blob/master/cmsis-core/core_cm0.h#L79. Our compiler-polyfill does not include asm at the moment.

**Comment by autopulated** [comment]
Sorry just noticed this – what does this enable, just raw `asm` use? You can anyway use the `__asm__` keyword, which I believe is what we do.

**Comment by autopulated** [comment]
bump @bremoran

**Comment by bremoran** [comment]
I had a specific use-case that this was blocking and I was able to fix it using a custom cmake instead.  I think that is the correct solution.

**Pull request closed without merging**
