### PR TITLE
Added gcov flag to generate relative path for .gcda files

### PR DESCRIPTION
**Pull request by mazimkhan**
Originally gcov compiled binary prints absolute path of `.gcda` files. The path is of the compilation host. This is not convenient in CI where we want to build in cloud and test on a physical host with hardware.

Added gcov flag `-fprofile-dir=.` so that target prints relative path to `.gcda` files. The path is relative to `<yotta module>/build/<yotta target>` as that is build home. This helps greentea in correctly saving `.gcda` files on a test slave (where pre built yotta module is copied). greentea checks if path is absolute or relative. relative paths are saved with prefix `build/<yotta target>/`

Coverage output without this change:

```
{{coverage_start;C:\Users\azikha01\Documents\GitHub\core-util-przemyslaw\build\frdm-k64f-gcc/source/CMakeFiles/core-util.dir/C_/Users/azikha01/Documents/GitHub/core-util-przemyslaw/source/sbrk.cpp.gcda}}
61646367723930343c403533000000a32f000000411cda458f000000010000009f0000000000000032000000000000003200000000000000a7000400000000000000000000000000000000000000000000000000000000005d00000000000000000
0000000000000000000001c00000001000000000000001c000000000000000a000000020000000000000014000000000000000800000005000000000000002800000000000000030000000700000000000000150000000000000001000000320000
0000000000320000000000000000000001030000006b000000a73ea86985f4a87f0000a1011200000002000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000002000000000000000
000000000000000020000000000000000000001030000006a000000874fc04d3eb2bbc00000a101040000000200000000000000020000000000000000000001030000006900000017b4039a6af8c1cb0000a1011000000001000000000000000000
00000000000006000000000000000600000000000000060000000000000006000000000000000000000000000000060000000000000000000000{{coverage_end}}
```

Coverage output after this change:

```
{{coverage_start;./source/CMakeFiles/core-util.dir/C_/Users/azikha01/Documents/GitHub/core-util-przemyslaw/source/sbrk.cpp.gcda}}
61646367723930343c403533000000a32f000000411cda458f000000010000009f0000000000000032000000000000003200000000000000a7000400000000000000000000000000000000000000000000000000000000005d00000000000000000
0000000000000000000001c00000001000000000000001c000000000000000a000000020000000000000014000000000000000800000005000000000000002800000000000000030000000700000000000000150000000000000001000000320000
0000000000320000000000000000000001030000006b000000a73ea86985f4a87f0000a1011200000002000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000002000000000000000
000000000000000020000000000000000000001030000006a000000874fc04d3eb2bbc00000a101040000000200000000000000020000000000000000000001030000006900000017b4039a6af8c1cb0000a1011000000001000000000000000000
00000000000006000000000000000600000000000000060000000000000006000000000000000000000000000000060000000000000000000000{{coverage_end}}
```

### CODE REVIEW

**Comment by bogdanm** [comment]
LGTM. Cc @PrzemekWirkus

**Comment by PrzemekWirkus** [comment]
+1

**Comment by PrzemekWirkus** [comment]
@bogdanm @bremoran How about a merger and post-Q1 release? :)

**Comment by bogdanm** [comment]
@PrzemekWirkus, the fix was published on the `gcda_fix` branch of this repository for now. Later we'll merge it and publish a new version.

**Comment by PrzemekWirkus** [comment]
@bogdanm, @mazimkhan Are we ready to add this change to master and publish?

**Comment by bogdanm** [comment]
Yup.

**Comment by bogdanm** [comment]
Published version 1.2.2

**Pull request merged**
