### PR TITLE
more friendly error messages if the compiler isn't found

### PR DESCRIPTION
**Pull request by autopulated**
cc @rgrover @jaustin 

Explicitly check for the programs that the toolchain needs, and generate more friendly error messages with useful instructions if they are not found.

### CODE REVIEW

**Comment by rgrover** [comment]
this looks good. Are we going to have some check for srec_cat?

**Comment by 0xc0170** [comment]
+1, I did quick test on windows

**Comment by autopulated** [comment]
yes! I'm planning to contribute that once I've dealt with some other things

**Comment by jaustin** [comment]
Awesome, thanks James. This will help a lot

**Pull request merged**
