### PR TITLE
enable floating point printf support, unless disabled by config value…

### PR DESCRIPTION
**Pull request by autopulated**
… 'gcc.printf-float = false'

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by hugovincent** [comment]
Needs explanation/instructions in the readme, other than that, +1.

**Comment by bogdanm** [comment]
Just realized that this might cause regressions (for example code size issues on nRF51822).

**Comment by hugovincent** [comment]
@bogdanm would having it default to off, with instructions to turn it on (and potentially e.g. turning it on by default in more resource-rich targets) help?

**Comment by bogdanm** [comment]
Cc @rgrover, since I think that leaving this on by default (which is probably the right thing to do) might have a big impact on nRF targets, but not much more. Also cc-ing @marcuschangarm, just in case :)

**Comment by pan-** [comment]
On nrf51822, this change add 14204 bytes to the final binary. 

By turning this ON by default, our users might pay a high price for what they don't use, without notice. I'm not sure this is desirable. 

If this flag is ON by default it would be good if we bump a major version and provide clear instruction explaining why binaries are fatter than before and how to turn this off.

**Comment by bogdanm** [comment]
What about leave it on by default, but turn it off explicitly for nRF targets? Would this work?

**Comment by autopulated** [comment]
I'd recommend against a major version bump for this, it isn't really a breaking change (we can't afford to treat everything that increases code size as a breaking change, for obvious reasons). If it's going to cause a problem on particular targets, I would recommend instead to update them first to change the default value, although this obviously detracts from a consistent cross-target user experience, so should only be where really needed.

**Comment by pan-** [comment]
@bogdanm For projects which use DFU and and run on 128k Flash target (like mkit), there is only 80k available for the user application. This mean that this change will decrease the space available to 66k. A simple application like the Eddystone beacon already eat 56k of memory, depending on the application, this change can be an issue. 

@autopulated While I agree that code size increase can't be considered as a breaking change at this stage in the life cycle of mbed-os, in this particular case, the increase is really huge. A developer working on a 128k FLASH target and doing firmware upgrade with a dual flash bank layout will have less than 64k available to his program. With this upgrade, it will either fail to link its program if its program occupy more than 80% of the available space or it will silently lose 20% of the space available. Do you think that losing so much space is  minor ? Do you think that link failures for some application is minor ?

**Comment by bogdanm** [comment]
I know I'm repeating myself, but:

> What about leave it on by default, but turn it off explicitly for nRF targets? Would this work?

:smile:

**Comment by ghost** [comment]
are the nrf targets the smallest across all boards? In any case, it will be slightly less of a penalty on the 256KB variants like the BLE Nano 1.5 and the NRF51 DK.  The NRF52  will be a different beast entirely.

**Comment by autopulated** [comment]
@bogdanm yup I think that's the right compromise here

**Comment by pan-** [comment]
@bogdanm I have talked with Rohit, we are happy if it is turned off by default on nrf51 targets.

**Comment by autopulated** [comment]
OK this is the config that's needed to do that:

``` JSON
"gcc": {
  "printf-float": false
}
```

**Comment by hugovincent** [comment]
@autopulated can you put that in the readme?

**Comment by bogdanm** [comment]
+1 && let's merge this!

**Comment by 0xc0170** [comment]
One question, `-u  _scanf_float` as part of this or not ?

**Comment by bogdanm** [comment]
Ah, very good question. Yes, I believe it `_scanf_float` should be part of this, to keep things consistent.

**Comment by autopulated** [comment]
I deliberately left _scanf_float out of the PR because the feature requests have explicitly been about printing. I think scanf-ing floats is probably less common.

**Comment by bogdanm** [comment]
So, consistency vs. practicality? What say you, @0xc0170? I'm inclined to go with James's suggestion and add `_scanf_float` later if needed. But I don't know what's the overhead of adding `_scanf_float` in the first place.

**Pull request merged**
