### PR TITLE
Fix #3 - use dwarf-3

### LINKED ISSUE #3: Invalid absolute module with uvision loader (gcc arm 4.8.4)
As some of you noticed, the debugging with uvision (me using 5.14) with this target results in the loader error, so no files are shown when debugging.

I recall it used to work a while ago when I might have used older gcc version (4.7), as I noticed in the release notes for GCC 4.8 which would explain it:

DWARF4 is now the default when generating DWARF debug information. When -g is used on a platform that uses DWARF debugging information, GCC will now default to -gdwarf-4 -fno-debug-types-section.
GDB 7.5, Valgrind 3.8.0 and elfutils 0.154 debug information consumers support DWARF4 by default. Before GCC 4.8 the default version used was DWARF2. To make GCC 4.8 generate an older DWARF version use -g together with -gdwarf-2 or -gdwarf-3. The default for Darwin and VxWorks is still -gdwarf-2 -gstrict-dwarf.

I checked uvision reference pages, it supports dwarf2 and dwarf3 options. I recall dwarf2 is used by default there. Therefore I quickly set -gdwarf-2 for compiler flags for gcc target, build a simple demo - which fixes this issue.

The above might help somebody to workaround the error in the loader module, but the question is - how we should fix this?

### PR DESCRIPTION
**Pull request by 0xc0170**
Differences for dwarf-4 (we might lose accepting this changeset):
(taken from dwarf4)
• Add support for new C++ language constructs, including rvalue references, generalized
  constant expressions, Unicode character types and template aliases.
• Clarify and generalize support for packed arrays and structures.
• Add new line number table support to facilitate profile based compiler optimization.
• Add additional support for template parameters in instantiations.
• Add support for strongly typed enumerations in languages (such as C++) that have two
  kinds of enumeration declarations.

This is just a proposal, feedback needed. We could forbid using gcc targets with uvision as they are not compatible with the newer gcc versions or let it be as it is - a user edits manually target to set dwarf to a version their debugger understands (uvision dwarf2/3).

Additional reading about uvision and newer dwarfs: https://answers.launchpad.net/gcc-arm-embedded/+question/271233.

@autopulated @bogdanm @bremoran

### CODE REVIEW

**Comment by bogdanm** [comment]
Interesting. Did you check that you can debug GCC built executables with MDK with this change in place?

**Comment by 0xc0170** [comment]
@bogdanm yes, tested with this change-set and before

**Comment by bogdanm** [comment]
I'd be inclined to give it a go then, but I'm curious what other people think about it.

**Comment by adbridge** [comment]
Could we have an optional compiler flag ? Default dwarf version is the latest but if you want to override it then you could do something like yt build -dwarf<x>  ?

**Comment by autopulated** [comment]
looks good to me. The advantages to using dwarf 4 over dwarf 3 are just incremental, so let's peg back at dwarf3 until uvision supports dwarf 4.

**Comment by autopulated** [comment]
published 0.1.2

**Pull request merged**
